### ISSUE TITLE
Incorrect path for libgio/gstreamer

### ISSUE THREAD

**Issue by brian-morgan-thomas** [laabicz/HomeLESS#3]
With the default locations for the files after the install the following error was occurring.  I was able to copy the gstreamer directory from lib to the application directory and allow the program to run correctly.

Starting video...

GSVideo version: 1.0.0
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: can't load library gio-2.0 (gio-2.0|libgio-2.0|li
bgio-2.0-0) with -Djna.library.path=C:/Users/Thomas/Downloads/HomeLess/HomeLESS_HA_1_2b_win32\gstreamer\windows32. Last
error:java.lang.UnsatisfiedLinkError: Unable to load library 'gio-2.0': The specified module could not be found.

```
    at codeanticode.gsvideo.GSLibraryLoader.loadLibrary(Unknown Source)
    at codeanticode.gsvideo.GSLibraryLoader.load(Unknown Source)
    at codeanticode.gsvideo.GSLibraryLoader.preLoadLibs(Unknown Source)
    at codeanticode.gsvideo.GSLibraryLoader.getInstance(Unknown Source)
    at codeanticode.gsvideo.GSVideo.initImpl(Unknown Source)
    at codeanticode.gsvideo.GSVideo.init(Unknown Source)
    at codeanticode.gsvideo.GSCapture.initGStreamer(Unknown Source)
    at codeanticode.gsvideo.GSCapture.<init>(Unknown Source)
    at HomeLESS_Hit_Analyzer.camera_setup(HomeLESS_Hit_Analyzer.java:884)
    at HomeLESS_Hit_Analyzer.setup(HomeLESS_Hit_Analyzer.java:132)
    at processing.core.PApplet.handleDraw(PApplet.java:2280)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
    at processing.core.PApplet.run(PApplet.java:2176)
    at java.lang.Thread.run(Unknown Source)
```

Terminate batch job (Y/N)? y

**Comment by laabicz** [comment]
Hi,
this is seems to be a "windows gstreamer" problem (described here: http://homeless-eng.webnode.com/hit-analyzer/troubleshooting/).
Sometimes this depend on version of Java Runtime Enviroment instaled on system. Because you can install 32bit version on 64bit system.
Try to move gstreamer library into different directory: ( ~/HitAnalyzer/gstreamer or ~/HitAnalyzer/lib/gstreamer) or use another version of Hit Analyzer (devel version): https://drive.google.com/folderview?id=0B4BISEuyQShpdGN2dFdnSGpyMVE&usp=sharing&tid=0B4BISEuyQShpUGVwUTIzY0t3QU0

Regards

Laabicz

**Comment by laabicz** [comment]
Hello!

Thank for you contacting us! At first I apologize for my very late response.
We appreciate you taking the time to write about interest in project Home
Laser Shooting.

This is a bug in GStreamer library. The library itself looking for ohter
component in directory depend on windows version (win 64/32 bit). The
solution is the move the library to right directory. Anyway, at new version
this will be fixed by using Processing video library.

Regards

Laabicz

2016-05-17 6:38 GMT+02:00 brian-morgan-thomas <notifications@github.com>:
