### ISSUE TITLE
i want to modify in java 

### ISSUE THREAD

**Issue by Akshay602** [laabicz/HomeLESS#5]
i want to modify the code in java eclipse but i have the following  error how to solve it and any insight on it will be help full....

Unable to load image from file 'graphics/general_settings_1.png'
The file "graphics/general_settings_1.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
Unable to load image from file 'graphics/general_settings_2.png'
The file "graphics/general_settings_2.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
The file "graphics/general_settings_3.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.Unable to load image from file 'graphics/general_settings_3.png'

Exception in thread "Animation Thread" java.lang.NullPointerException
    at g4p_controls.GImageButton.<init>(Unknown Source)
    at g4p_controls.GImageButton.<init>(Unknown Source)
    at HomeLESS_Hit_Analyzer1.create_button_win_genereal_settings(HomeLESS_Hit_Analyzer1.java:269)
    at HomeLESS_Hit_Analyzer1.setup(HomeLESS_Hit_Analyzer1.java:114)
    at processing.core.PApplet.handleDraw(PApplet.java:2280)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
    at processing.core.PApplet.run(PApplet.java:2176)
    at java.lang.Thread.run(Thread.java:745)

**Comment by laabicz** [comment]
Hello!

Thank for you contacting us! At first I apologize for my very late response.
We appreciate you taking the time to write about interest in project Home
Laser Shooting.

The source code is writen in Processing language (it is similar to Java).
So is not possible to directly modify this code in eclipse. But you can
free download Processing IDE from webiste processing.org .

Regards

Laabicz

2016-06-11 9:20 GMT+02:00 Akshay602 notifications@github.com:

**Comment by Akshay602** [comment]
hello sir,

how do i import this project in processing ide please be kind to send me
the procedure in chronological order.

Thanks & Regards
Akshay
