### ISSUE TITLE
NullPointerException in "Animation Thread"

### ISSUE THREAD

**Issue by Palciny** [laabicz/HomeLESS#6]
Hi guys,
I have a problem with running Hit_Analyzer both Linux and Windows version.

Stack trace:
(java.exe:11356): Glib-GObject-CRITICAL **: file ..\..\..\gobject\gobject.c: lin
e 2299: assertion `G_IS_OBJECT (object)' failed

** (java.exe:11356): CRITICAL **: file ..\..\..\Source\gstreamer\gst\gstelement.
c: line 3119: assertion `GST_IS_ELEMENT (element)' failed
Exception in thread "Animation Thread" java.lang.NullPointerException
        at org.gstreamer.Pipeline.initBus(Pipeline.java:161)
        at org.gstreamer.Pipeline.<init>(Pipeline.java:116)
        at codeanticode.gsvideo.GSCapture.initGStreamer(Unknown Source)
        at codeanticode.gsvideo.GSCapture.<init>(Unknown Source)
        at HomeLESS_Hit_Analyzer.camera_setup(HomeLESS_Hit_Analyzer.java:884)
        at HomeLESS_Hit_Analyzer.setup(HomeLESS_Hit_Analyzer.java:132)
        at processing.core.PApplet.handleDraw(PApplet.java:2280)
        at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)

        at processing.core.PApplet.run(PApplet.java:2176)
        at java.lang.Thread.run(Unknown Source)

Is there any workaround?

**Comment by jdlee77** [comment]
See this post: https://github.com/laabicz/HomeLESS/issues/3

**Comment by Palciny** [comment]
Fixed, forgot to close.
